# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    dir
  displayName: 'npm install and build'
  
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(4b89f88e-13f2-4990-bf5f-3ab2e4d5301f)'
    appType: 'webApp'
    appName: 'yusufzerdazi'
    package: 'build'
    deploymentMethod: 'auto'

- task: PurgeAzureCDNEndpoint@2
  inputs:
    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
    ConnectedServiceNameARM: 'Pay-As-You-Go(4b89f88e-13f2-4990-bf5f-3ab2e4d5301f)'
    ResourceGroupName: 'yusufzerdazi'
    EndpointName: 'yusufzerdazi'
    ProfileName: 'yusufzerdazi'
    PurgeContent: '/*'