@startuml stock
!include styles.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/AIMachineLearning/AzureCognitiveServices.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/google.puml
!include DEVICONS/react.puml
!include DEVICONS/raspberry_pi.puml
!include FONTAWESOME/mobile.puml

Container(function, "Azure Function", "C#", "Polls every minute for items in stock.")
Container(ifttt, "IFTTT", "App")
Container_Ext(phone, "Phone", "Notification")

Rel_R(function, ifttt, "Calls webhook")
Rel_R(ifttt, phone, "Sends notification")

HIDE_STEREOTYPE()

@enduml