@startuml dreams
!include styles.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/AIMachineLearning/AzureCognitiveServices.puml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/google.puml

Container_Ext(keep, "Google Keep", "API", "I write my dreams as a notes in Google Keep.", "google")
Container(function, "Azure Function", "Python", "Polls Google Keep once a day for new dreams.", "AzureFunction")
Container(ml, "Cognitive Services", "Azure", "The dreams are analysed using cognitive services.", "AzureCognitiveServices")
ContainerDb(db, "Blob Storage", "Blob", "The dreams, along with the analysed info are saved to blob storage.", "AzureBlobStorage")
Container_Ext(bi, "Power BI", "App", "I use Power BI to build graphs and reports based on the blob files.")

Rel_L(function, keep, "Makes API calls to", "HTTP")
Rel_R(function, db, "Writes to", "HTTP")
Rel_D(function, ml, "Makes API calls to", "HTTP")
Rel_U(bi, db, "Reads from")

HIDE_STEREOTYPE()

@enduml