@startuml feeder
!include styles.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/AIMachineLearning/AzureCognitiveServices.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/google.puml
!include DEVICONS/raspberry_pi.puml

Container(pi, "Raspberry Pi", "Package", "Camera set up to detect motion.", "raspberry_pi")
Container(ml, "Cognitive Services", "Azure", "The image is analysed using cognitive services.", "AzureCognitiveServices")
Container(arduino, "Arduino", "C", "Hooked up to a motor which dispenses food.")

Rel_R(pi, ml, "Makes API calls to", "HTTP")
Rel_D(pi, arduino, "Triggers", "Bluetooth")

HIDE_STEREOTYPE()

@enduml