@startuml lights
!include styles.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/AIMachineLearning/AzureCognitiveServices.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/google.puml
!include DEVICONS/react.puml
!include DEVICONS/raspberry_pi.puml
!include FONTAWESOME/mobile.puml

Container(tasker, "Tasker", "App")
Container(ifttt, "IFTTT", "Webhook")
Container_Ext(hive, "Hive", "IOT")
Container_Ext(smartlife, "Smart Life", "IOT")

Rel_R(tasker, ifttt, "Calls Webhook")
Rel_R(ifttt, hive, "Turns lights on/off")
Rel_D(ifttt, smartlife, "Turns plugs on/off")

HIDE_STEREOTYPE()

@enduml