// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Yusuf.Zerdazi.Data;

namespace Yusuf.Zerdazi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171104230558_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Yusuf.Zerdazi.Web.Models.Everyday", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int?>("MonthID");

                    b.Property<bool>("OriginalAudio");

                    b.Property<bool>("OriginalImage");

                    b.Property<string>("SourceAudio");

                    b.Property<string>("SourceImageTitle");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("MonthID");

                    b.ToTable("Everydays");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Web.Models.Month", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AudioID");

                    b.Property<int?>("ImageID");

                    b.Property<DateTime>("Start");

                    b.HasKey("ID");

                    b.HasIndex("AudioID");

                    b.HasIndex("ImageID");

                    b.ToTable("Months");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Web.Models.Theme", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Web.Models.Everyday", b =>
                {
                    b.HasOne("Yusuf.Zerdazi.Web.Models.Month", "Month")
                        .WithMany()
                        .HasForeignKey("MonthID");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Web.Models.Month", b =>
                {
                    b.HasOne("Yusuf.Zerdazi.Web.Models.Theme", "Audio")
                        .WithMany()
                        .HasForeignKey("AudioID");

                    b.HasOne("Yusuf.Zerdazi.Web.Models.Theme", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID");
                });
#pragma warning restore 612, 618
        }
    }
}
