// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Yusuf.Zerdazi.Data;
using Yusuf.Zerdazi.Shared.Enums;

namespace Yusuf.Zerdazi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180327221242_AddMonthBackgrounds")]
    partial class AddMonthBackgrounds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Everyday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int?>("MonthId");

                    b.HasKey("Id");

                    b.HasIndex("MonthId");

                    b.ToTable("Everydays");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<DateTime?>("Fulfilled");

                    b.Property<DateTime>("Requested");

                    b.HasKey("Id");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Month", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImageUrl");

                    b.Property<DateTime>("Start");

                    b.HasKey("Id");

                    b.ToTable("Months");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Piece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EverydayId");

                    b.Property<bool>("Explicit");

                    b.Property<int?>("SourceId");

                    b.Property<int?>("ThemeId");

                    b.Property<string>("Title");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("EverydayId");

                    b.HasIndex("SourceId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Pieces");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Medium");

                    b.Property<int?>("MonthId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("MonthId");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Everyday", b =>
                {
                    b.HasOne("Yusuf.Zerdazi.Data.Models.Month")
                        .WithMany("Everydays")
                        .HasForeignKey("MonthId");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Piece", b =>
                {
                    b.HasOne("Yusuf.Zerdazi.Data.Models.Everyday")
                        .WithMany("Pieces")
                        .HasForeignKey("EverydayId");

                    b.HasOne("Yusuf.Zerdazi.Data.Models.Piece", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.HasOne("Yusuf.Zerdazi.Data.Models.Theme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Theme", b =>
                {
                    b.HasOne("Yusuf.Zerdazi.Data.Models.Month")
                        .WithMany("Themes")
                        .HasForeignKey("MonthId");
                });
#pragma warning restore 612, 618
        }
    }
}
