// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Yusuf.Zerdazi.Data;
using Yusuf.Zerdazi.Data.Models;

namespace Yusuf.Zerdazi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180213212150_AddMeals")]
    partial class AddMeals
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Everyday", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int?>("MonthID");

                    b.HasKey("ID");

                    b.HasIndex("MonthID");

                    b.ToTable("Everydays");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<DateTime?>("Fulfilled");

                    b.Property<DateTime>("Requested");

                    b.HasKey("Id");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Month", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Start");

                    b.HasKey("ID");

                    b.ToTable("Months");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Piece", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EverydayID");

                    b.Property<bool>("Explicit");

                    b.Property<int?>("SourceID");

                    b.Property<int?>("ThemeID");

                    b.Property<string>("Title");

                    b.Property<string>("URL");

                    b.HasKey("ID");

                    b.HasIndex("EverydayID");

                    b.HasIndex("SourceID");

                    b.HasIndex("ThemeID");

                    b.ToTable("Pieces");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Theme", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Medium");

                    b.Property<int?>("MonthID");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("MonthID");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Everyday", b =>
                {
                    b.HasOne("Yusuf.Zerdazi.Data.Models.Month")
                        .WithMany("Everydays")
                        .HasForeignKey("MonthID");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Piece", b =>
                {
                    b.HasOne("Yusuf.Zerdazi.Data.Models.Everyday")
                        .WithMany("Pieces")
                        .HasForeignKey("EverydayID");

                    b.HasOne("Yusuf.Zerdazi.Data.Models.Piece", "Source")
                        .WithMany()
                        .HasForeignKey("SourceID");

                    b.HasOne("Yusuf.Zerdazi.Data.Models.Theme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeID");
                });

            modelBuilder.Entity("Yusuf.Zerdazi.Data.Models.Theme", b =>
                {
                    b.HasOne("Yusuf.Zerdazi.Data.Models.Month")
                        .WithMany("Themes")
                        .HasForeignKey("MonthID");
                });
#pragma warning restore 612, 618
        }
    }
}
