on:
  push:
    paths:
    - '**.bicep'
    - .github/workflows/bicep.yml
  workflow_dispatch:

name: infrastructure

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: yusufzerdazi
        template: ./bicep/main.bicep
        failOnStdErr: false
      
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.52.0
        inlineScript: |
          az storage blob service-properties update --account-name yusufzerdazi --static-website --404-document error.html --index-document index.html
