name: web

on:
  push:
    paths:
    - src/**
    - plantuml/**
    - public/**
    - .github/workflows/web.yml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - uses: actions/checkout@main

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        
    - run: npm ci
    - name: npm run build
      run: npm run build --if-present
      env:
        CI: ""

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.52.0
        inlineScript: |
          az storage blob delete-batch --account-name yusufzerdazi --source '$web'
          az storage blob upload-batch --destination '$web' --account-name yusufzerdazi --source ./build --overwrite
          az cdn endpoint purge -g yusufzerdazi -n yusufzerdazi --profile-name yusufzerdazi --content-paths "/*"

  