name: web

on:
  push:
    paths:
    - 'src/**'
    - 'public/**'
    - '*.json'
    - '*.ts'
    - '*.html'
    - '.env.production'
    - '*.cjs'
    - '.github/workflows/web.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - uses: actions/checkout@main

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        
    - run: npm ci
    - name: npm run build
      run: npm run build --if-present
      env:
        CI: ""

    - name: Deploy to Azure Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name yusufzerdazi --source '$web'
          az storage blob upload-batch --destination '$web' --account-name yusufzerdazi --source ./dist --overwrite

    - name: Purge Cloudflare Cache
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/4476610d017411183cad4e529c2854ba/purge_cache" \
          -H "Content-Type: application/json" \
          -H "X-Auth-Email: ${{ secrets.CLOUDFLARE_EMAIL }}" \
          -H "X-Auth-Key: ${{ secrets.CLOUDFLARE_API_KEY }}" \
          -d '{"purge_everything": true}'

  